//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSalute
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int codCliente { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string numEndereco { get; set; }
        public string telefone { get; set; }
        public string celular2 { get; set; }
        public string celular1 { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public string profissao { get; set; }
        public string estadoCivil { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string sexo { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public string compEndereco { get; set; }
    
        public virtual Enderecos Enderecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
