//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSalute
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.Profissionais = new HashSet<Profissionais>();
        }
    
        public int codConsulta { get; set; }
        public double valor { get; set; }
        public System.DateTime agenda { get; set; }
        public string status { get; set; }
        public string sala { get; set; }
        public string formaPagamento { get; set; }
        public string parcelamento { get; set; }
        public bool comissao { get; set; }
    
        public virtual Tratamentos Tratamentos { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profissionais> Profissionais { get; set; }
    }
}
